version: "3.9"
services:
  postgis:
    #image: "postgis/postgis:15-3.3"
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    #volumes:
    #  - "./postgresql_data:/var/lib/postgresql/data"
    ports:
      - "15432:5432"