# Generated by Django 4.1.5 on 2023-01-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='speech_file',
            field=models.FileField(blank=True, null=True, upload_to='speech/'),
        ),
    ]
